name: Run lint and build
on: [push]

jobs:
  run:
    name: Lint and build
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@master

      - name: Set Node.js version
        uses: actions/setup-node@master
        with:
          node-version: 16
      
      - name: Install yarn
        run: npm i -g yarn

      - run: node --version
      - run: yarn --version

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
