name: Run lint and build
on: [push]

jobs:
  run:
    name: Lint and build
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - run: node --version
      - run: yarn --version

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
