name: Run lint and build
on: [push, pull_request]

jobs:
  run:
    name: Node 12
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Clone repository
        uses: actions/checkout@master

      - name: Set Node.js version
        uses: actions/setup-node@v1.1.0
        with:
          version: 12
      
      - name: Install yarn
        run: npm i yarn -g

      - run: node --version
      - run: yarn --version

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
